export const currencyByNaira: CurrencyProp[] = [
  {
    name: 'DOLLAR',
    value: 1652.51,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 1764.35,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 2036.3,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 17.77,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 1065.88,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 981.81,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 9.26,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 5385.69,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 38333150,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'SWISS FRANC',
    value: 1820.74,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'SOUTH AFRICAN RAND',
    value: 87.74,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'INDIAN RUPEE',
    value: 19.89,
    flag: '🇮🇳',
    symbol: '₹',
  },
  {
    name: 'PAKISTANI RUPEE',
    value: 5.61,
    flag: '🇵🇰',
    symbol: '₨',
  },
  {
    name: 'BANGLADESHI TAKA',
    value: 15.55,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'EGYPTIAN POUND',
    value: 53.54,
    flag: '🇪🇬',
    symbol: 'E£',
  },
  {
    name: 'MEXICAN PESO',
    value: 92.35,
    flag: '🇲🇽',
    symbol: 'MX$',
  },
  {
    name: 'BRAZILIAN REAL',
    value: 334.75,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'TURKISH LIRA',
    value: 60.22,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'PHILIPPINE PESO',
    value: 29.38,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 1211.41,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'MALAYSIAN RINGGIT',
    value: 354.28,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'THAI BAHT',
    value: 46.21,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'UAE DIRHAM',
    value: 449.81,
    flag: '🇦🇪',
    symbol: 'AED',
  },
  {
    name: 'QATARI RIYAL',
    value: 453.72,
    flag: '🇶🇦',
    symbol: '﷼',
  },
  {
    name: 'SAUDI RIYAL',
    value: 440.23,
    flag: '🇸🇦',
    symbol: '﷼',
  },
  {
    name: 'OMANI RIAL',
    value: 4289.57,
    flag: '🇴🇲',
    symbol: '﷼',
  },
  {
    name: 'CHINESE YUAN',
    value: 225.25,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 210.76,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'INDONESIAN RUPIAH',
    value: 0.11,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'KENYAN SHILLING',
    value: 11.3,
    flag: '🇰🇪',
    symbol: 'KSh',
  },
  {
    name: 'UGANDAN SHILLING',
    value: 0.44,
    flag: '🇺🇬',
    symbol: 'USh',
  },
  {
    name: 'GHANAIAN CEDI',
    value: 142.24,
    flag: '🇬🇭',
    symbol: '₵',
  },
  {
    name: 'ETHIOPIAN BIRR',
    value: 29.46,
    flag: '🇪🇹',
    symbol: 'Br',
  },
  {
    name: 'ZAMBIAN KWACHA',
    value: 84.75,
    flag: '🇿🇲',
    symbol: 'ZK',
  },
  {
    name: 'TANZANIAN SHILLING',
    value: 0.67,
    flag: '🇹🇿',
    symbol: 'TSh',
  },
  {
    name: 'RWANDAN FRANC',
    value: 1.39,
    flag: '🇷🇼',
    symbol: 'FRw',
  },
  {
    name: 'SIERRA LEONE LEONE',
    value: 0.08,
    flag: '🇸🇱',
    symbol: 'Le',
  },
  {
    name: 'MOROCCAN DIRHAM',
    value: 151.24,
    flag: '🇲🇦',
    symbol: 'MAD',
  },
  {
    name: 'BOTSWANA PULA',
    value: 120.87,
    flag: '🇧🇼',
    symbol: 'P',
  },
  {
    name: 'MAURITIAN RUPEE',
    value: 37.12,
    flag: '🇲🇺',
    symbol: '₨',
  },
  {
    name: 'MADAGASCAR ARIARY',
    value: 0.36,
    flag: '🇲🇬',
    symbol: 'Ar',
  },
];
